USE INFOADB;

SELECT * FROM TB_AGENDA;

INSERT INTO TB_AGENDA(NM_CONTATO, DS_TELEFONE, DS_EMAIL, BT_FAVORITO, DT_CADASTRO)
		VALUES ('KLEBER', '(11) 95894730', 'KLEBERREIDELAS@GMAIL.COM', FALSE, '2023-05-23');
-- YG        

SELECT *
FROM TB_AGENDA
WHERE NM_CONTATO LIKE "%K%";

SELECT *
FROM TB_AGENDA
WHERE BT_FAVORITO = 1;

SELECT *
FROM TB_AGENDA
WHERE DT_CADASTRO BETWEEN '2023/03/20' AND '2023/05/30';

UPDATE TB_AGENDA
SET NM_CONTATO = 'ROGERIO',
	DS_TELEFONE = '(11) 9094753',
    DS_EMAIL = 'ROGERIOGASMEPLAYS@GMAIL.COM',
    BT_FAVORITO = 1,
    DT_CADASTRO = '2020/03/02'
    WHERE ID_AGENDA = 1;
    
DELETE FROM TB_AGENDA
WHERE ID_AGENDA = 1;

